- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/Svydovets-Bobocode-Java-Ultimate-core.yml
- .github/workflows/formatter.yml
- .mvn/jvm.config
- pom.xml
- settings.xml
- src/test/java/TestCodeAnalysis.java
[Create CI](https://trello.com/c/9fR6Iclo)
Added the request template. Added the CI pipeline using GitHub actions. Added google formatting.
https://github.com/marketplace/actions/google-java-format
https://github.com/google/google-java-format
> #5 Create CI

- .github/workflows/formatter.yml
[Create CI](https://trello.com/c/9fR6Iclo)
Added permissions
https://github.com/Svydovets-Bobocode-Java-Ultimate-3-0/Bring/pull/2
> BR-5: Create CI

- src/main/java/svydovets/core/annotation/Configuration.java
- src/main/java/svydovets/core/context/DefaultApplicationContext.java
- src/main/java/svydovets/util/BeanNameResolver.java
- src/test/java/com/bobocode/svydovets/util/BeanNameResolverTest.java
Implement logic for bean name resolving
Write logic for bean name resolving
Added/updated
-
-
> BR-22 Write logic for bean name resolving

- src/main/java/svydovets/core/context/DefaultApplicationContext.java
- src/main/java/svydovets/util/ReflectionsUtil.java
- src/test/java/com/bobocode/svydovets/util/ReflectionUtilTest.java
[BR-21](https://trello.com/c/XsODabJR)
Added the logic for establishing the beans if they are annotated with `@Qualifier` or `@Primary` annotations.
Tested manually. Wrote a couple of unit tests for the `@Qualifier` annotation.
> BR-21: Implement @Primary and @Qualifier

- src/main/java/svydovets/core/context/DefaultApplicationContext.java
- src/main/java/svydovets/core/context/injector/AbstractInjector.java
- src/main/java/svydovets/core/context/injector/BeanInjector.java
- src/main/java/svydovets/core/context/injector/CollectionInjector.java
- src/main/java/svydovets/core/context/injector/Injector.java
- src/main/java/svydovets/core/context/injector/InjectorConfig.java
- src/main/java/svydovets/core/context/injector/InjectorExecutor.java
- src/main/java/svydovets/core/context/injector/MapOfBeansInjector.java
> Refactor injection

- src/main/java/svydovets/core/context/AnnotationConfigApplicationContext.java
- src/main/java/svydovets/core/context/beanDefinition/BeanDefinitionFactory.java
- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
- src/main/java/svydovets/util/PackageScanner.java
- src/main/java/svydovets/util/ReflectionsUtil.java
- src/test/java/com/bobocode/svydovets/config/BeanConfigForPackageScanner.java
- src/test/java/com/bobocode/svydovets/config/NonAnnotatedClass.java
- src/test/java/com/bobocode/svydovets/core/ApplicationContextTest.java
- src/test/java/com/bobocode/svydovets/core/AutowireTest.java
- src/test/java/com/bobocode/svydovets/core/PostConstructTest.java
- src/test/java/com/bobocode/svydovets/util/PackageScannerTest.java
- src/test/java/com/bobocode/svydovets/withoutAnnotation/NonAnnotatedClass.java
BR-23 IoC container architecture has been refactored
1) DefaultApplicationContext class renamed to AnnotationConfigApplicationContext 
2) Logic of "DefaultApplicationContext" moved to new classes:
* BeanFactory
* BeanDefinitionFactory
> BR-23 IoC container architecture has been refactored

- src/main/java/svydovets/util/ReflectionsUtil.java
- src/test/java/com/bobocode/svydovets/util/ReflectionUtilTest.java
> BR-24: Add test to ReflectionUtils

- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
- src/main/java/svydovets/core/context/injector/AbstractInjector.java
- src/test/java/com/bobocode/svydovets/core/ApplicationContextTest.java
- src/test/java/com/bobocode/svydovets/core/AutowireTest.java
- src/test/java/com/bobocode/svydovets/core/PostConstructTest.java
- src/test/java/com/bobocode/svydovets/service/base/NullService.java
- src/test/java/com/bobocode/svydovets/service/base/OrderService.java
- src/test/java/com/bobocode/svydovets/util/BeanNameResolverTest.java
> BR-19 add setter autowire injection

- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
> BR-42: fix methods "getBean" in "BeanFactory"

- src/main/java/svydovets/core/context/beanDefinition/BeanDefinitionFactory.java
- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
- src/main/java/svydovets/exception/NoUniqueBeanDefinitionException.java
- src/main/java/svydovets/util/ErrorMessages.java
- src/test/java/com/bobocode/svydovets/ioc/core/autowire/injector/MapOfBeansInjectorTest.java
- src/test/java/com/bobocode/svydovets/ioc/core/context/ApplicationContextTest.java
- src/test/java/com/bobocode/svydovets/source/autowire/collection/CollectionsHolderService.java
- src/test/java/com/bobocode/svydovets/source/autowire/constructor/ServiceWithAutowiredConstructor.java
- src/test/java/com/bobocode/svydovets/source/config/PrimaryPackageBeansConfig.java
- src/test/java/com/bobocode/svydovets/source/primary/FirstPrimaryServiceImpl.java
- src/test/java/com/bobocode/svydovets/source/primary/PrimaryService.java
- src/test/java/com/bobocode/svydovets/source/primary/SecondPrimaryServiceImpl.java
> BR-34 Add tests for application context

- src/main/java/svydovets/core/context/AnnotationConfigApplicationContext.java
- src/main/java/svydovets/core/context/ApplicationContext.java
- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
> BR-41: add method getContext to ApplicationContext

- pom.xml
- src/main/java/svydovets/exception/UnsupportedTypeException.java
- src/main/java/svydovets/web/DispatcherServlet.java
- src/main/java/svydovets/web/WebInvocationHandler.java
- src/main/java/svydovets/web/annotation/DeleteMapping.java
- src/main/java/svydovets/web/annotation/GetMapping.java
- src/main/java/svydovets/web/annotation/PatchMapping.java
- src/main/java/svydovets/web/annotation/PathVariable.java
- src/main/java/svydovets/web/annotation/PostMapping.java
- src/main/java/svydovets/web/annotation/PutMapping.java
- src/main/java/svydovets/web/dto/RequestInfoHolder.java
- src/main/java/svydovets/web/path/RequestInfo.java
- src/main/java/svydovets/web/path/RequestInfoCreator.java
- src/test/java/com/bobocode/svydovets/web/WebInvocationHandlerTest.java
- src/test/java/com/bobocode/svydovets/web/controller/UserController.java
- src/test/java/com/bobocode/svydovets/web/dto/User.java
- src/test/java/com/bobocode/svydovets/web/factory/UserFactory.java
> BR-Web Create basic implementation of method argument resolving 

- src/test/java/com/bobocode/svydovets/ioc/core/autowire/AutowiredFieldAnnotationBeanPostProcessorTest.java
- src/test/java/com/bobocode/svydovets/ioc/core/autowire/AutowiredMethodAnnotationBeanPostProcessorTest.java
- src/test/java/com/bobocode/svydovets/ioc/core/beanDefinitionFactory/BeanDefinitionFactoryTest.java
- src/test/java/com/bobocode/svydovets/source/autowire/constructor/ConstructorInjectionService.java
- src/test/java/com/bobocode/svydovets/source/autowire/constructor/ConstructorInjectionServiceWithoutAutowire.java
- src/test/java/com/bobocode/svydovets/source/autowire/constructor/InjectionCandidate.java
- src/test/java/com/bobocode/svydovets/source/autowire/constructor/InjectionCandidate2.java
- src/test/java/com/bobocode/svydovets/source/config/AutowireByFieldPackageBeansConfig.java
- src/test/java/com/bobocode/svydovets/source/config/AutowireByMethodPackageBeansConfig.java
> BR-37 Cover "BeanDefinitionFactory" class by tests

- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
> BRW-48: Refactor method "defineSpecificBean()" in "BeanFactory"

- src/main/java/svydovets/web/dto/RequestInfoHolder.java
- src/main/java/svydovets/web/dto/ResponseEntity.java
- src/test/java/com/bobocode/svydovets/web/dto/HttpHeadersTest.java
- src/test/java/com/bobocode/svydovets/web/dto/RequestInfoHolderTest.java
- src/test/java/com/bobocode/svydovets/web/dto/ResponseEntityTest.java
> BR-54: Cover dto package with test

- src/main/java/svydovets/core/context/beanDefinition/BeanDefinitionFactory.java
- src/test/java/com/bobocode/svydovets/ioc/core/beanDefinitionFactory/BeanDefinitionFactoryTest.java
- src/test/java/com/bobocode/svydovets/source/autowire/method/CopyService.java
- src/test/java/com/bobocode/svydovets/source/autowire/method/PopulateService.java
- src/test/java/com/bobocode/svydovets/source/autowire/method/PrintLnService.java
- src/test/java/com/bobocode/svydovets/source/config/BasePackageWithAdditionalBeansConfig.java
- src/test/java/com/bobocode/svydovets/source/config/ConfigWithThrowScope.java
> BR-38: Cover the implementations of "BeanDefinition" with tests

- src/test/java/com/bobocode/svydovets/ioc/core/beanFactory/BeanFactoryTest.java
> BR-51: Cover "BeanFactory" class with tests

- README.md
- src/main/java/svydovets/core/context/AnnotationConfigApplicationContext.java
- src/main/java/svydovets/core/context/beanDefinition/BeanDefinitionFactory.java
- src/main/java/svydovets/core/context/beanFactory/BeanFactory.java
- src/main/java/svydovets/core/context/beanFactory/BeanFactoryImpl.java
- src/main/java/svydovets/util/PackageScanner.java
- src/main/java/svydovets/web/AnnotationConfigWebApplicationContext.java
- src/test/java/com/bobocode/svydovets/ioc/core/beanFactory/BeanFactoryImplTest.java
Write a documentation and README
> BR-53 Write a documentation and README

- README.md
- src/main/java/svydovets/core/context/beanFactory/BeanFactoryImpl.java
- src/main/java/svydovets/util/PackageScanner.java
Write a documentation and README
> Br 53 Write a documentation and README

- README.md
- pom.xml
> BR: update pom.xml and README.md

- src/main/java/svydovets/web/annotation/DeleteMapping.java
- src/main/java/svydovets/web/annotation/GetMapping.java
- src/main/java/svydovets/web/annotation/PostMapping.java
- src/main/java/svydovets/web/annotation/PutMapping.java
> Java docs annotations

- README.md
> Add README for the ResponseEntity
